services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    env_file:
      - .env
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
    driver: bridge
