// Code generated by ent, DO NOT EDIT.

package ent

import (
	"planningpoker/ent/room"
	"planningpoker/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	roomFields := schema.Room{}.Fields()
	_ = roomFields
	// roomDescName is the schema descriptor for name field.
	roomDescName := roomFields[0].Descriptor()
	// room.NameValidator is a validator for the "name" field. It is called by the builders before save.
	room.NameValidator = roomDescName.Validators[0].(func(string) error)
	// roomDescHash is the schema descriptor for hash field.
	roomDescHash := roomFields[1].Descriptor()
	// room.HashValidator is a validator for the "hash" field. It is called by the builders before save.
	room.HashValidator = roomDescHash.Validators[0].(func(string) error)
}
